### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'button_box'

### ISSUE THREAD

**Issue by mnahmad** [KonstiDE/Bestagon#3]
Hi All
I install the plugin on mac (Ventura 13.1), however, when I started the plugin, I got the following error. 

```
AttributeError: 'NoneType' object has no attribute 'button_box' 
Traceback (most recent call last):
  File "/Users/test/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Bestagon-master/bestagon.py", line 248, in run
    self.dlg.button_box.buttons()[2].clicked.connect(show_help)
AttributeError: 'NoneType' object has no attribute 'button_box'


Python version: 3.8.7 (default, Feb 10 2021, 09:04:08) [Clang 12.0.0 (clang-1200.0.32.29)] 
QGIS version: 3.18.3-Zürich Zürich, 735cc85be9 

Python Path:
/Applications/QGIS.app/Contents/MacOS/../Resources/python
/Users/test/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/test/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/click_plugins-1.1.1-py3.8.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/pandas-1.1.0-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/netCDF4-1.5.4-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/affine-2.3.0-py3.8.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/opencv_contrib_python-4.3.0.36-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/pyproj-2.6.0-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/Pillow-7.2.0-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/geopandas-0.8.1-py3.8.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/numba-0.50.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/GDAL-3.2.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/patsy-0.5.1-py3.8.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/statsmodels-0.11.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/Rtree-0.9.4-py3.8.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/rasterio-1.1.5-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/lib-dynload
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/Fiona-1.8.13.post1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/scipy-1.5.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/snuggs-1.4.7-py3.8.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/numpy-1.20.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python38.zip
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/cftime-1.2.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-macosx-10.13.0-x86_64.egg
/Users/test/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/test/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/HCMGIS/forms
/Users/test/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis_resource_sharing
/Users/test/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis_resource_sharing/ext_libs
```

**Comment by KonstiDE** [comment]
Seems like an implementation error, I'll look into it

**Comment by KonstiDE** [comment]
Hello, @mnahmad 
I pushed a fix a few minutes ago, please check if the error still occurs for you. I tested on Windows 10, QGIS 3.24 Tisler

**Comment by mnahmad** [comment]
HI @KonstiDE, pulled latest code, the previous error is solved but now getting this error 

```
An error has occurred while executing Python code: 

AttributeError: 'QgsMapLayerComboBox' object has no attribute 'setPlaceholderText' 
Traceback (most recent call last):
  File "/Users/test/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Bestagon/bestagon.py", line 223, in run
    self.dlg = bestagonDialog()
  File "/Users/test/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Bestagon/bestagon_dialog.py", line 44, in __init__
    self.setupUi(self)
  File "", line 164, in setupUi
  File "", line 174, in retranslateUi
AttributeError: 'QgsMapLayerComboBox' object has no attribute 'setPlaceholderText'


Python version: 3.8.7 (default, Feb 10 2021, 09:04:08) [Clang 12.0.0 (clang-1200.0.32.29)] 
QGIS version: 3.18.3-Zürich Zürich, 735cc85be9 

Python Path:
/Applications/QGIS.app/Contents/MacOS/../Resources/python
/Users/test/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/test/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/pandas-1.1.0-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/affine-2.3.0-py3.8.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/rasterio-1.1.5-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages
/Applications/QGIS.app/Contents/MacOS/lib/python3.8
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/pyproj-2.6.0-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/statsmodels-0.11.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/netCDF4-1.5.4-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/numba-0.50.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python38.zip
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/click_plugins-1.1.1-py3.8.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/geopandas-0.8.1-py3.8.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/lib-dynload
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/Rtree-0.9.4-py3.8.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/Fiona-1.8.13.post1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/opencv_contrib_python-4.3.0.36-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/scipy-1.5.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/snuggs-1.4.7-py3.8.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/patsy-0.5.1-py3.8.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/cftime-1.2.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/GDAL-3.2.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/numpy-1.20.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/Pillow-7.2.0-py3.8-macosx-10.13.0-x86_64.egg
/Users/test/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/test/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/HCMGIS/forms
/Users/test/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis_resource_sharing
/Users/test/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis_resource_sharing/ext_libs
/Users/test/work/Projects/Regreening-Africa/RegreeningAfrica_Stakeholder_interaction_data/Kenya/nurseries
```

**Comment by KonstiDE** [comment]
Interesting, as on my system everthing works fine... I will pushed another fix later this day

**Comment by KonstiDE** [comment]
@mnahmad are you sure you pulled the recent github .zip folder, uninstalled the previous version and reinstalled via the .zip file?

Because I never use the method from the error message `setPlaceholderText` ?!?

**Comment by mnahmad** [comment]
@KonstiDE yes I did uninstall the plugin, then went to the repo and downloaded as zipped file (bestagon.py updated 3/4 days ago), decompressed the zipped file in plugin folder and restarted QGIS as well.

**Comment by KonstiDE** [comment]
@mnahmad I could not figure it out yet.. Maybe try on a different system? I also tried it on a mac, worked fine...

**Comment by KonstiDE** [comment]
Closed due to inactivity
