### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by skampus** [KonstiDE/Bestagon#4]
Hi,
I receive this error in all QGIS versione (Dev, LTR, LTR dev, stable).
Is a problem due to my installation?
Thank you.

stefano
______

2023-10-15T19:33:40     CRITICAL    Traceback (most recent call last):
              File "C:\OSGeo4W/apps/qgis-ltr-dev/./python\qgis\utils.py", line 423, in _startPlugin
              plugins[packageName] = package.classFactory(iface)
              File "C:\Users/Campus/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Bestagon-master\__init__.py", line 35, in classFactory
              from .bestagon import bestagon
              File "C:\OSGeo4W/apps/qgis-ltr-dev/./python\qgis\utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\Users/Campus/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Bestagon-master\bestagon.py", line 45, in 
              from .bestagon_dialog import bestagonDialog
              File "C:\OSGeo4W/apps/qgis-ltr-dev/./python\qgis\utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\Users/Campus/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Bestagon-master\bestagon_dialog.py", line 31, in 
              FORM_CLASS, _ = uic.loadUiType(os.path.join(
              File "C:\OSGeo4W/apps/qgis-ltr-dev/./python\qgis\PyQt\uic\__init__.py", line 36, in __loadUiType
              return __PyQtLoadUiType(*args, **kwargs)
              File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\__init__.py", line 200, in loadUiType
              winfo = compiler.UICompiler().compileUi(uifile, code_string, from_imports,
              File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\Compiler\compiler.py", line 111, in compileUi
              w = self.parse(input_stream, resource_suffix)
              File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 1037, in parse
              actor(elem)
              File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 828, in createUserInterface
              self.traverseWidgetTree(elem)
              File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
              handler(self, child)
              File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 273, in createWidget
              self.traverseWidgetTree(elem)
              File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
              handler(self, child)
              File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 273, in createWidget
              self.traverseWidgetTree(elem)
              File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
              handler(self, child)
              File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 273, in createWidget
              self.traverseWidgetTree(elem)
              File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
              handler(self, child)
              File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 503, in createLayout
              self.traverseWidgetTree(elem)
              File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
              handler(self, child)
              File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 546, in handleItem
              self.traverseWidgetTree(elem)
              File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
              handler(self, child)
              File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 264, in createWidget
              self.stack.push(self.setupObject(widget_class, parent, elem))
              File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 230, in setupObject
              self.wprops.setProperties(obj, branch)
              File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\properties.py", line 415, in setProperties
              prop_value = self.convert(prop, widget)
              File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\properties.py", line 378, in convert
              return func(prop[0], **args)
              File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\properties.py", line 120, in _set
              expr = [self._pyEnumMember(v) for v in prop.text.split('|')]
              File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\properties.py", line 120, in 
              expr = [self._pyEnumMember(v) for v in prop.text.split('|')]
              File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\properties.py", line 115, in _pyEnumMember
              raise NoSuchClassError(prefix)
             PyQt5.uic.exceptions.NoSuchClassError: Unknown C++ class: QgsMapLayerProxyModel

**Comment by KonstiDE** [comment]
Hi, I was able to reproduce the error quite easily. Please find the new version in the git and install the plugin via GitHub.

PyQt seems to have a problem with the QgsMapLayerProxyModel class, so I omitted it. The disadvantage is that now I cannot use filters, but I will look for a workaround in the future.

@skampus 

Please test and let me know if the latest commit worked for you :)

**Comment by skampus** [comment]
All works fine!
thanks a lot

stefano
